# Generated by Django 4.2.6 on 2023-10-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_rename_category_parentcategory_childcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
