# Generated by Django 4.2.6 on 2023-10-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area_code', models.TextField(max_length=100)),
                ('primary_phone', models.IntegerField(max_length=100)),
                ('Street_address', models.TextField(max_length=100)),
                ('Zip_code', models.IntegerField(max_length=100)),
                ('business_address', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
