# Generated by Django 4.2.6 on 2023-11-01 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_remove_shippingaddress_street_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=100)),
                ('title_2', models.CharField(max_length=100)),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('specs_1', models.TextField()),
                ('specs_2', models.TextField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_infos', to='ecomapp.product')),
            ],
        ),
    ]
