# Generated by Django 4.2.6 on 2023-11-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0020_additionalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='specs_1',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='specs_2',
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='camera_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='camera_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='capacity_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='capacity_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='chip_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='chip_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='display_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='display_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='video_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='video_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='weightanddimensions_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='weightanddimensions_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='title_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='title_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
