# Generated by Django 4.2.6 on 2023-11-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0021_remove_additionalinfo_description_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinfo',
            old_name='camera_1',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='camera_2',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='capacity_1',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='capacity_2',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='chip_1',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='chip_2',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='display_1',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='display_2',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='video_1',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='video_2',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='weightanddimensions_1',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='weightanddimensions_2',
        ),
    ]
