# Generated by Django 4.2.6 on 2023-11-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0022_rename_camera_1_additionalinfo_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
