# Generated by Django 4.2.6 on 2023-11-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0024_rename_description_additionalinfo_description_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='title_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='title_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
